psql -U postgres -d postgres <<EOF
CREATE USER $POSTGRES_USERNAME WITH ENCRYPTED PASSWORD '$POSTGRES_USERPASS';
ALTER USER $POSTGRES_USERNAME WITH SUPERUSER CREATEROLE CREATEDB REPLICATION BYPASSRLS;
CREATE DATABASE $POSTGRES_DBNAME;
EOF