psql -U postgres -d postgres <<EOF
CREATE USER $POSTGRES_USER_NAME WITH ENCRYPTED PASSWORD '$POSTGRES_USER_PASS';
ALTER USER $POSTGRES_USER_NAME WITH SUPERUSER CREATEROLE CREATEDB REPLICATION BYPASSRLS;
CREATE DATABASE $POSTGRES_DBNAME;
EOF